FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Aponta para o arquivo main.py que está dentro da pasta backend
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]